name: Test Backoffice

on:
  push:
    branches:
      - contrib
      - release/*
      - v*/dev
  pull_request:
    branches:
      - contrib
      - release/*
      - v*/dev

  # Allows GitHub to use this workflow to validate the merge queue
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_OPTIONS: --max_old_space_size=16384

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: src/Umbraco.Web.UI.Client/.nvmrc
          cache: npm
          cache-dependency-path: ./src/Umbraco.Web.UI.Client/package-lock.json
      - run: npm ci --no-audit --no-fund --prefer-offline
        working-directory: src/Umbraco.Web.UI.Client
      - run: npm run lint:errors
        working-directory: src/Umbraco.Web.UI.Client
      - run: npx playwright install --with-deps
        working-directory: src/Umbraco.Web.UI.Client
      - run: npm test
        working-directory: src/Umbraco.Web.UI.Client
      - run: npm run check:paths
        working-directory: src/Umbraco.Web.UI.Client
      - run: npm run generate:jsonschema:dist
        working-directory: src/Umbraco.Web.UI.Client
